# DeltaBans Configuration File (Bungee)

# Delay between every save of bans.json and warnings.json
MinutesPerBanSave: 5

# Delay between removing old warnings
MinutesPerWarningCleanup: 120

# Duration of warnings in minutes (10080 = 1 week)
WarningDuration: 10080

# Enable whitelist by default
Whitelist: False

# Formatting
Formats:

  PermanentBanMessage: "{0} - {1}\n\nThis ban is a permanent ban."
  TemporaryBanMessage: "{0} - {1}\n\nThis ban is temporary and will expire in:\n{3}"
  RangeBanMessage: "{0} - {1}\n\nIf you need to be exempted from this range ban, contact an administrator of this server."

  SilentPrefix: '&8[&6Silent&8]&6'
  BanAnnouncement: '&8[&6Ban&8]&6 &f{0}&6 banned &f{1}&6 for &f{2}&6.'
  UnbanAnnouncement: '&8[&6Unban&8]&6 &f{0}&6 unbanned &f{1}&6.'
  TempBanAnnouncement: '&8[&6Ban&8]&6 &f{0}&6 temp-banned &f{1}&6 for &f{2}&6.'
  RangeBanAnnouncement: '&8[&6Ban&8]&6 &f{0}&6 range-banned &f{1}&6 for &f{2}&6.'
  RangeUnbanAnnouncement: '&8[&6Unban&8]&6 &f{0}&6 unbanned &f{1}&6 IP ranges that overlapped with &f{2}&6'
  WarnAnnouncement: '&8[&6Warn&8]&6 &f{0}&6 warned &f{1}&6 for &f{2}&6.'

  AddedToRangeBanWhitelist: '&8[&a!&8] &aSuccess &8[&a!&8]&7 Added &f{0}&7 to range-ban whitelist.'
  AlreadyInRangeBanWhitelist: '&8[&c!&8] &cFailure &8[&c!&8]&7 &f{0}&7 is already in the range-ban whitelist.'
  RemovedFromRangeBanWhitelist: '&8[&a!&8] &aSuccess &8[&a!&8]&7 Removed &f{0}&7 from range-ban whitelist.'
  NotInRangeBanWhitelist: '&8[&c!&8] &cFailure &8[&c!&8]&7 &f{0}&7 is not in the range-ban whitelist.'

  WhitelistMessage: '&8[&6!&8]&7=&8[&6 Server is currently in whitelist mode. &8]&7=&8[&6!&8]'
  WhitelistToggle: '&8[&a!&8] &aSuccess &8[&a!&8]&7 Whitelist has been &f{0}&7.'
  AddedToWhitelist: '&8[&a!&8] &aSuccess &8[&a!&8]&7 Added &f{0}&7 to whitelist.'
  AlreadyInWhitelist: '&8[&c!&8] &cFailure &8[&c!&8]&7 &f{0}&7 is already in the whitelist.'
  RemovedFromWhitelist: '&8[&a!&8] &aSuccess &8[&a!&8]&7 Removed &f{0}&7 from whitelist.'
  NotInWhitelist: '&8[&c!&8] &cFailure &8[&c!&8]&7 &f{0}&7 is not in the whitelist.'

  RemovedWarnings: '&8[&a!&8] &aSuccess &8[&a!&8]&7 Removed &f{0}&7 warnings for &f{1}&7.'

  SaveSucess: '&8[&a!&8] &aSuccess &8[&a!&8]&7 Bans, warnings, range-whitelist, and whitelist have been saved.'
  SaveFailure: '&8[&c!&8] &cFailure &8[&c!&8]&7 There was an error saving. More details available in the BungeeCord logs.'

  AlreadyIpBanned: '&8[&c!&8] &cFailure &8[&c!&8]&7 &f{0}&7 is already ip-banned.'
  AlreadyNameBanned: '&8[&c!&8] &cFailure &8[&c!&8]&7 &f{0}&7 is already name-banned.'
  BanNotFound: '&8[&c!&8] &cFailure &8[&c!&8]&7 Ban not found for &f{0}&7.'

# Used for debugging DeltaBans
DebugMode: False
