# DeltaBans Configuration File

# DbShare Database name
Database: Main

# Database table used by xAuth to save account information
xAuth-AccountsTable: accounts

# Default message to show on ban
DefaultBanMessage: 'You have been banned from this server!'

# Default message to show on temp ban
DefaultTempBanMessage: 'You have been temporarily banned from this server!'

# Default message to show on range ban
DefaultRangeBanMessage: 'You have been IP range banned from this server!'

# Default message to show on warning
DefaultWarningMessage: 'You have been warned!'

# Commands to run on a specific number of warnings
# {name} Name of the player that was warned
# {message} Message that was sent as part of the warning
WarningCommands:
  1:
  - 'tell {name} {message}'
  2:
  - 'kick {name} {message}'
  3:
  - 'tempban {name} 1m {message}'

# Used for debugging DeltaBans
DebugMode: False
