# DeltaBans Configuration File

# DbShare Database name
Database: Main

# Database table used by xAuth to save account information
xAuth-AccountsTable: accounts

# Formatting
Formats:

  DefaultBanMessage: 'You have been banned from this server!'
  DefaultTempBanMessage: 'You have been temporarily banned from this server!'
  DefaultRangeBanMessage: 'You have been IP range banned from this server!'
  DefaultWarningMessage: 'You have been warned!'
  DefaultKickMessage: 'You have been kicked!'

  KickMessageToPlayer: 'You have been kicked by {0} for {1}.'
  KickMessageToAnnounce: '{0} was kicked by {1} for {2}.'

# Commands to run on a specific number of warnings
# {name} Name of the player that was warned
# {message} Message that was sent as part of the warning
WarningCommands:
  1:
  - 'tell {name} {message}'
  2:
  - 'kick {name} {message}'
  3:
  - 'tempban {name} 1m {message}'

# Used for debugging DeltaBans
DebugMode: False
