name: DeltaBans
main: com.yahoo.tracebachi.DeltaBans.Spigot.DeltaBansPlugin
version: 1.1
author: Trace Bachi (tracebachi@yahoo.com, BigBossZee)
depend: [DeltaRedis, xAuth]
commands:
  ban:
    description: Allows the user to ban others and their IP.
    aliases: [dban]
  unban:
    description: Allows the user to unban others.
    aliases: [dunban]
  tempban:
    description: Allows the user to ban others for a duration.
    aliases: [dtempban]
  nameban:
    description: Allows the user to ban names instead of IPs.
    aliases: [dnameban]
  checkban:
    description: Allows the user to check if names or IPs are banned.
    aliases: [dcheckban]
  savebans:
    description: Allows the user to force a ban file save.

permissions:
  DeltaRedis.Ban:
    description: Main permission for banning and unbanning.
  DeltaRedis.CheckBan:
    description: Permission for checking bans.
  DeltaRedis.SaveBans:
    description: Permission for forcing ban save.
