name: DeltaBans
main: com.yahoo.tracebachi.DeltaBans.Spigot.DeltaBansPlugin
version: 1.2
author: Trace Bachi (tracebachi@yahoo.com, BigBossZee)
depend: [DeltaRedis, xAuth]
commands:
  ban:
    description: Allows the user to ban others and their IP.
    aliases: [deban]
  unban:
    description: Allows the user to unban others.
    aliases: [deunban]
  tempban:
    description: Allows the user to ban others for a duration.
    aliases: [detempban]
  nameban:
    description: Allows the user to ban names instead of IPs.
    aliases: [denameban]
  banned:
    description: Allows the user to check if names or IPs are banned.
    aliases: [debanned]
  warn:
    description: Allows the user to issue warnings.
    aliases: [dewarn]
  unwarn:
    description: Allows the user to pardon a single warning.
    aliases: [deunwarn]
  rangeban:
    description: Allows the user to ban an ip range.
    aliases: [derangeban]
  deltabanssave:
    description: Allows the user to force save ban and warning files.

permissions:
  DeltaBans.Ban:
    description: Main permission for banning and unbanning.
  DeltaBans.RangeBan:
    description: Main permission for range banning.
  DeltaBans.CheckBan:
    description: Permission for checking bans.
  DeltaBans.CheckBan.Extra:
    description: Permission for checking bans (only ban message and banner shown).
  DeltaBans.Warn:
    description: Permission for issuing warnings.
  DeltaBans.Save:
    description: Permission for forcing save of ban and warning files.
