name: DeltaBans
main: com.gmail.tracebachi.DeltaBans.Spigot.DeltaBans
version: 1.4
author: Trace Bachi (tracebachi@gmail.com, BigBossZee)
depend: [DeltaRedis, xAuth]
commands:
  ban:
    description: Allows the user to ban others and their IP.
    aliases: [dbban]
  unban:
    description: Allows the user to unban others.
    aliases: [dbunban]
  tempban:
    description: Allows the user to ban others for a duration.
    aliases: [dbtempban]
  nameban:
    description: Allows the user to ban names instead of IPs.
    aliases: [dbnameban]
  banned:
    description: Allows the user to check if names or IPs are banned.
    aliases: [dbbanned]
  kick:
    description: Allows the user to kick others.
    aliases: [dbkick]
  warn:
    description: Allows the user to issue warnings.
    aliases: [dbwarn]
  unwarn:
    description: Allows the user to pardon a single warning.
    aliases: [dbunwarn]
  rangeban:
    description: Allows the user to ban an ip range.
    aliases: [dbrangeban]
  rangeunban:
    description: Allows the user to unban an ip range.
    aliases: [dbrangeunban]
  rangewhitelist:
    description: Allows the user to whitelist a name in a rangeban.
  deltabanssave:
    description: Allows the user to force save ban and warning files.

permissions:
  DeltaBans.Ban:
    description: Main permission for banning and unbanning.
  DeltaBans.RangeBan:
    description: Main permission for range banning.
  DeltaBans.CheckBan:
    description: Permission for checking bans.
  DeltaBans.CheckBan.Extra:
    description: Permission for checking bans (only ban message and banner shown).
  DeltaBans.Warn:
    description: Permission for issuing warnings.
  DeltaBans.Kick:
    description: Permission for kicking.
  DeltaBans.Save:
    description: Permission for forcing save of ban and warning files.
